name: Publish
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          persist-credentials: false
      - name: Install and Build ğŸ”§
        run: |
          yarn install
          yarn test
          yarn build
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Deploy version
        uses: mikeal/merge-release@master
        id: deploy
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Commit version
        run: |
          git config --global user.email $(git --no-pager show -s --format='%ae' HEAD)
          git config --global user.name $(git --no-pager show -s --format='%an' HEAD)
          npm version ${{ steps.deploy.outputs.version }} -m "[skip ci] bump version"
          git push origin master
